### PR TITLE
fix for the board not printing properly... again

### PR DESCRIPTION
**Pull request by ZeroOne010101**

### CODE REVIEW

**Comment by Levi-Lesches** [comment]
Does this actually work? By reversing the rows and not the individual cells, you're not turning the board 180°, you're simply reordering the rows. For example, the king and queen will not be flipped when it is Black's turn

**Comment by ZeroOne010101** [comment]
@Levi-Lesches Black is still using self.mirror, so they get flipped.

**Comment by Levi-Lesches** [comment]
As long as it works. Does it work on your computer?

**Comment by ZeroOne010101** [comment]
@Levi-Lesches Yes

**Comment by Levi-Lesches** [comment]
Alright great, thanks for pushing this

**Pull request merged**
